### PR TITLE
feat: modify randomness values to drop hashing in input and output

### PR DESCRIPTION
**Pull request by arajasek**
Integrates a change produced by https://github.com/filecoin-project/ref-fvm/pull/1842

### CODE REVIEW

**Comment by Stebalien** [comment]
I think we need to drop these vectors entirely as the "randomness" part (the "return" value) is also wrong. It needs to be the randomness _before_ hashing with the entropy, etc.

**Comment by arajasek** [comment]
@Stebalien Sorry, this isn't ready for review yet -- my plan is to replace the returns with the digests. It's easy enough to do that from Lotus, I just need to write a script for it.

**Comment by Stebalien** [comment]
@arajasek by extracting them from the chain? Because we can't invert the hash.

**Comment by Stebalien** [comment]
Ooh. You did! Having a lotus dev on the team is so very useful.

**Review by Stebalien — APPROVED** [review]
LGTM assuming it works!

**Comment by arajasek** [comment]
(Worked locally)

**Pull request merged**
